### ISSUE TITLE
features without geometries

### ISSUE THREAD

**Issue by Jannik-Schilling** [Jannik-Schilling/generate_swmm_inp#26]
Hola, tengo un error que no he podido solucionar, 

reading shapfiles
done
reading tables
done
preparing data for input file
Traceback (most recent call last):
File "C:/Users/danie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_swmm_inp\generate_swmm_inp_file.py", line 438, in processAlgorithm
junctions_df['X_Coord'],junctions_df['Y_Coord'] = get_coords_from_geometry(junctions_df)
TypeError: cannot unpack non-iterable NoneType object

La ejecución falló después de 0.02 segundos

se trata de las coordenadas pero no logro resolverlo

agradecería  mucho tu ayuda

![Error](https://user-images.githubusercontent.com/98361171/150876160-6325cd20-d810-4781-b9ed-5c557c61d52f.png)

_Originally posted by @danieles-93 in https://github.com/Jannik-Schilling/generate_swmm_inp/issues/6#issuecomment-1020617924_

**Comment by danieles-93** [comment]
Hola, puedes compartirme unos archivos para ver cómo "Gnerate inp" pasa el
archivo Inp a archivos shp y xls?

**Comment by danieles-93** [comment]
Muchas gracias, con la opción ImportInpFile no he logrado tener éxito. Los
ejemplos fueron de mucha ayuda.

Muchas gracias
