### ISSUE TITLE
Error when trying to generate INP File

### ISSUE THREAD

**Issue by OkunoShio** [Jannik-Schilling/generate_swmm_inp#42]
Hello!

I was really excited when discovering your plugin - however unfortunately I get this error when I try to export my data to INP.

![grafik](https://user-images.githubusercontent.com/104507082/199520097-fc233fb2-d7c4-476b-b1d2-76acd6e79c36.png)

I first thought the issue lies within my data, however I tried the same process with the default data. Any help would be very much appreciated!

I tried on QGIS versions 3.10.14 and 3.16.10.
PIP 22.3
Pandas 1.1.5
Openpyxl 3.0.10

**Comment by Jannik-Schilling** [comment]
oh... you´re right. That´s a bug. I´ll fix that. You can install version 0.23 instead: https://plugins.qgis.org/plugins/generate_swmm_inp/version/0.23/

**Comment by Jannik-Schilling** [comment]
fixed with 11ca52c
