### ISSUE TITLE
[enhancement] add RDII to the script 

### ISSUE THREAD

**Issue by MMR100** [Jannik-Schilling/generate_swmm_inp#54]
It would be very interesting to add RDII to the inflows table (currently only "direct" and "dry weather" are available).

**Comment by Jannik-Schilling** [comment]
Hm, good idea. What do you think about adding it to the file of the other inflows? I´d try to make it part of the next version of the plugin.

**Comment by MMR100** [comment]
That would be perfect ! 
Today as a workaround I create an Excel sheet with the necessary columns and I copy / paste them into the inp file via notepad.

**Comment by Jannik-Schilling** [comment]
0f5da8b5040864495ad4c3cbbe5c230196cc2301

**Comment by Jannik-Schilling** [comment]
60762cc9446056434cceefbd50c64573720c157d

**Comment by MMR100** [comment]
wonderful!
Then (https://github.com/Jannik-Schilling/generate_swmm_inp/issues/2#issue-945596878) can be updated for RDII section.
