### ISSUE TITLE
Remember previous values

### ISSUE THREAD

**Issue by MMR100** [Jannik-Schilling/generate_swmm_inp#56]
I use several time "generateSWMMinpfile" script before reaching the final SWMM model. 
Therefore in would be nice if the layer previously used is selected by default in the list of layer. 
For the first time use of the script, the default layer could be the name from script 1 "generatedefaultdata".

**Comment by Jannik-Schilling** [comment]
Hi, I won´t make this part of the plugin, because there is already a possibility to do this in QGIS (for all available processing tools). You simply go to: Processing > History. Then, to re-run the tool with the previously selected layers and files you double-click on the last item in the list.

**Comment by MMR100** [comment]
Thank you. I didn't know this functionnality.
