### ISSUE TITLE
Barrels from qgis to swmm

### ISSUE THREAD

**Issue by luciano-Almiron** [Jannik-Schilling/generate_swmm_inp#57]
Hi, your app is amazing, thanks for sharing.
We are having an issue with the barrels in conduits.
Even when we modify the barrels in the example file, them don't change from "1" in the swmm inp file.
can you help us?

**Comment by Jannik-Schilling** [comment]
Hey, thank you for reporting this issue. The plugin writes the number of barrels correctly into the input file but as a floating point number.  It seems like SWMM only accepts integers, here. I´ll fix that in the next release.

**Comment by Jannik-Schilling** [comment]
[cb1e83a](https://github.com/Jannik-Schilling/generate_swmm_inp/commit/cb1e83a5221ffc34dc0d842b49f02dce03930754)

**Comment by luciano-Almiron** [comment]
hi.
Yes, that's exactly what we just discovered. So we were fixing it from the input file.
Thanks for the magic

**Comment by Jannik-Schilling** [comment]
[615210c](https://github.com/Jannik-Schilling/generate_swmm_inp/commit/615210cd7bb09cc9432f0be702b1af6c75613b33)
