### ISSUE TITLE
Can't name the conduit columns as "Shape"

### ISSUE THREAD

**Issue by Utsav1234567** [Jannik-Schilling/generate_swmm_inp#78]
When I try to rename the attribute column for any shapefile to "Shape", QGIS returns an error message "_Invalid field name. This field name is reserved and cannot be used_." . Without renaming the column to Shape, I am not able to create inp file using the conduit shapefile. 

Any solution to this problem?

**Comment by Mariosmsk** [comment]
Export your data as a GeoPackage.
Add a new column named `Shape` to the GeoPackage.
Re-export the data to a shapefile

**Comment by Jannik-Schilling** [comment]
https://github.com/Jannik-Schilling/generate_swmm_inp/commit/62305086da33ade61687356a5ca05350c5f52d93

**Comment by Jannik-Schilling** [comment]
After some discussions, the column name "Shape" will be replaced by "XsectShape". In the next versions of the plugin, a deprecation warning will appear.
