### ISSUE TITLE
Can't see any buttons or options to execute the tools of the plugin.

### ISSUE THREAD

**Issue by Crones8** [Jannik-Schilling/generate_swmm_inp#88]
Hello Jannik,

Sadly I write with a problem, I've installed the plugin and I can't seem to find any of the tools anywhere on my QGIS UI. Installed the latest version of panda. however that didn't seem to fix it. I've installed, reinstalled, uninstalled, and then installed again, however I can't find the function anywhere.

QGIS Version is 3.28.10 .
OS is Windows 10.

Here's some Screenshots to see if it can be helpful to identify the problem.

![image](https://github.com/Jannik-Schilling/generate_swmm_inp/assets/165178174/e565de29-7671-45e7-b4fb-9bcfb4f6fcf0)

![image](https://github.com/Jannik-Schilling/generate_swmm_inp/assets/165178174/823e1fe5-9753-463d-b426-dad761c38a83)
![image](https://github.com/Jannik-Schilling/generate_swmm_inp/assets/165178174/dd359044-65ed-4ce2-a791-61260fb604f0)

**Comment by Crones8** [comment]
Ah, Thank you so much, I did find it there.

Sorry for being so, for lack of a better word, ignorant.

I will suggest though, since people like me exist, it would be useful to put this same image in the manual.

The plugin worked flawlessly, it is a huge help, don't know if I can donate or anything, but, it will save me so much time. So Thank you so much for creating it.

Cheers, and sorry for wasting time.

**Comment by Jannik-Schilling** [comment]
added to readme and documentation: [96d0fcb](https://github.com/Jannik-Schilling/generate_swmm_inp/pull/89/commits/96d0fcb385ef893a51e651a715b7307d29220461), [c9c5167](https://github.com/Jannik-Schilling/generate_swmm_inp/pull/89/commits/c9c516715ffa2f2767b115057775a04efcc18e2d)

**Comment by Crones8** [comment]
Thank you so much, saw that it was added to the installation chapter.
