### ISSUE TITLE
How to set up network from existing nodes and pipes in QGIS

### ISSUE THREAD

**Issue by MikeDowner** [Jannik-Schilling/generate_swmm_inp#93]
Hi Jannik,
I have imported into QGIS shapefiles for pipes and manholes for a wastewater network. I have your plugin generate swmm. How can I get the conduit attribute table to populate the from node and to node (manholes) without manually inputting them, there is about 170 manholes.

Thanks,
Mike

**Comment by Jannik-Schilling** [comment]
Hi Mike,

you can use QGIS processing tools to prepare your data: 

1. "**Extract specific vertices**" (from pipes) with vertex index **0** for the first vertex of each pipe (=starting nodes)
2.  with the extracted points: "**join by nearest**" with the manholes as layer 2 (join layer); fields to join: name of the manhole; as the result you get a points layer with the name of the pipe and the starting point
3. in the pipes´ layer properties make a join with the resulting layer from step 2. Join field and target field are the pipes names; select only the name of the nodes in the list of "joined fields" 
4. use the field calculator to copy the information of the joined nodes names to the column "FromNode"

Repeat steps 1-4 with vertex index **-1** in step 1 to get the last vertex (recieving nodes) of each pipe and rename to "ToNode" in step 4.

Regards
Jannik

**Comment by MikeDowner** [comment]
Thank you Jannik, much appreciated.

Mike Roberts
Senior Projects Engineer
Utilities

***@***.***


M | +64274904132
E | ***@***.***
750 Lower Queen Street
Richmond Tasman 7081
www.downergroup.co.nz
<http://www.downergroup.co.nz>
***@***.***

**Comment by MikeDowner** [comment]
Hi Jannik,
Sorry to ask but I am getting errors when I try and generate the inp and can’t find why. Attached are the two shp files I want to use TOTSM_WW_Trunk_Features1 as junctions, TOTSM_WW_Trunk_Pipes as conduits.

***@***.***

Could you take a look as point me in the right direction?

Much appreciated.


Mike Roberts
Senior Projects Engineer
Utilities

***@***.***


M | +64274904132
E | ***@***.***
750 Lower Queen Street
Richmond Tasman 7081
www.downergroup.co.nz
<http://www.downergroup.co.nz>
***@***.***

**Comment by Jannik-Schilling** [comment]
Hi Mike,
as far as I know, you cannot sent attachments to github via mail. 

There are two things to check: 

1. are the geometries of the features in the layers valid (e.g. not empty)?
2. did you write suitable values in the attribute table?  Here, you can have a look at the documentation file.
